#:schema node_modules/wrangler/config-schema.json
name = "waterfall"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./assets/", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "404-page" }

[[d1_databases]]
binding = "DB"
database_name = "waterfall-db"
database_id = "78a0ff80-7914-404e-b54e-431477ff677f"